spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/learning_community
      auto-index-creation: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: 'false'
server:
  port: 8080
